# Generated by Django 2.0.5 on 2018-08-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180807_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsol',
            name='descripcion',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
