# Generated by Django 2.0.5 on 2018-08-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_itemsol_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsol',
            name='descripcion',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
