# Generated by Django 2.0.5 on 2018-08-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180807_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(choices=[('U', 'Unidad'), ('M3', 'Metros cúbicos'), ('Kg', 'Kilogramos.')], default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='itemsol',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UnidadesDeMedida'),
        ),
    ]
