# Generated by Django 2.0.5 on 2018-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180808_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsol',
            name='unidad',
            field=models.CharField(choices=[('U', 'Unidad'), ('M3', 'Metros cúbicos'), ('Kg', 'Kilogramos.')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='UnidadesDeMedida',
        ),
    ]
