# Generated by Django 2.0.5 on 2018-08-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_materialreal_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreal',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
