# Generated by Django 2.0.5 on 2018-08-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_materialreal_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategoria',
            fields=[
                ('categoria', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
