# Generated by Django 2.0.5 on 2018-08-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_materialcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
