# Generated by Django 2.0.5 on 2018-08-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180812_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsol',
            name='categoria',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='materialabstracto',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
