# Generated by Django 2.0.5 on 2018-08-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180812_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialabstracto',
            name='categoria',
        ),
    ]
