# Generated by Django 2.0.5 on 2018-08-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_materialabstracto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialabstracto',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
