# Generated by Django 2.0.5 on 2018-08-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='comentarios',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='precio',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='respondido',
            field=models.CharField(default='no', max_length=30),
        ),
    ]
