# Generated by Django 2.0.5 on 2018-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180814_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='proveedor',
            field=models.CharField(default='', max_length=30),
        ),
    ]
