# Generated by Django 2.0.5 on 2018-08-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_cotizacion_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Proveedor'),
        ),
    ]
