# Generated by Django 2.0.5 on 2018-08-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180814_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='comentarios',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
    ]
